#!/usr/bin/env bash
# A Bash script that transfers a file from a client to a server:

# Check if 4 arguments are passed to the script
if [[ "$#" -lt 4 ]]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Allocate the arguments to variables

file_path=$1
ip=$2
username=$3
ssh_key=$4

# Deactivate strict host key checking for the ssh connection
ssh_options="-o StrictHostKeyChecking=no"


scp -i "$ssh_key" $ssh_options "$file_path" "$username@$ip":~
